title: Add the MicroPython firmware
hero_image: images/banner.png
description: add-micropython-firmware description
version: 4
listed: false
copyedit: false
last_tested: "2022-01-24"
steps:
  - title: Introduction
  - title: Step title
  - title: What next?
